steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/chatbot:$COMMIT_SHA', '.']
    dir: 'Chatbot'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/chatbot:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'chatbot'
      - '--image'
      - 'gcr.io/$PROJECT_ID/chatbot:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '60s'
      - '--set-env-vars'
      - 'GROQ_API_KEY=${_GROQ_API_KEY}'

images:
  - 'gcr.io/$PROJECT_ID/chatbot:$COMMIT_SHA'

substitutions:
  _GROQ_API_KEY: ''

options:
  logging: CLOUD_LOGGING_ONLY
